### ISSUE TITLE
Add Logging functionality

### ISSUE THREAD

**Issue by Dastyni** [andyjko/pltutor#89]
Add the ability to log the timestamp of each action taken by the user.

**Comment by ddmiller1995** [comment]
Dependent on User identification (#100)

**Comment by ddmiller1995** [comment]
Set up to save moves and answers with timestamp per script to sessionStorage. Does not yet discriminate per visitation, simply appends to end of previous visit. Also has to be manually collected from computers until back end with user identification is built.
